# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GermanyMasc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(978, 910)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.TitleLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.TitleLayout.setObjectName(_fromUtf8("TitleLayout"))
        self.TitleLabel = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rockwell"))
        font.setPointSize(24)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName(_fromUtf8("TitleLabel"))
        self.TitleLayout.addWidget(self.TitleLabel)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(580, 10, 191, 111))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.EnglishBtnLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.EnglishBtnLayout.setObjectName(_fromUtf8("EnglishBtnLayout"))
        self.EnglishBtn = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.EnglishBtn.setFont(font)
        self.EnglishBtn.setObjectName(_fromUtf8("EnglishBtn"))
        self.EnglishBtnLayout.addWidget(self.EnglishBtn)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(770, 10, 191, 111))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.GermanBtnLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.GermanBtnLayout.setObjectName(_fromUtf8("GermanBtnLayout"))
        self.GermanBtn = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.GermanBtn.setFont(font)
        self.GermanBtn.setObjectName(_fromUtf8("GermanBtn"))
        self.GermanBtnLayout.addWidget(self.GermanBtn)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(380, 10, 161, 111))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.ZoomLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.ZoomLayout.setObjectName(_fromUtf8("ZoomLayout"))
        self.ZoomBox = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.ZoomBox.setFont(font)
        self.ZoomBox.setObjectName(_fromUtf8("ZoomBox"))
        self.ZoomLayout.addWidget(self.ZoomBox)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 140, 461, 81))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.CountryInfoLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.CountryInfoLayout.setObjectName(_fromUtf8("CountryInfoLayout"))
        self.CountryInfoLabel = QtGui.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CountryInfoLabel.setFont(font)
        self.CountryInfoLabel.setObjectName(_fromUtf8("CountryInfoLabel"))
        self.CountryInfoLayout.addWidget(self.CountryInfoLabel)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(500, 140, 461, 81))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.UniInfoLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.UniInfoLayout.setObjectName(_fromUtf8("UniInfoLayout"))
        self.UniInfoLabel = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UniInfoLabel.setFont(font)
        self.UniInfoLabel.setObjectName(_fromUtf8("UniInfoLabel"))
        self.UniInfoLayout.addWidget(self.UniInfoLabel)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 230, 161, 161))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.CountryPicLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.CountryPicLayout.setObjectName(_fromUtf8("CountryPicLayout"))
        self.CountryPicLabel = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.CountryPicLabel.setObjectName(_fromUtf8("CountryPicLabel"))
        self.CountryPicLayout.addWidget(self.CountryPicLabel)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(800, 230, 161, 161))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.UniPicLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.UniPicLayout.setObjectName(_fromUtf8("UniPicLayout"))
        self.UniPicLabel = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.UniPicLabel.setObjectName(_fromUtf8("UniPicLabel"))
        self.UniPicLayout.addWidget(self.UniPicLabel)
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(180, 230, 291, 161))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.CountryTextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.CountryTextLayout.setObjectName(_fromUtf8("CountryTextLayout"))
        self.CountryTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_9)
        self.CountryTextEdit.setObjectName(_fromUtf8("CountryTextEdit"))
        self.CountryTextLayout.addWidget(self.CountryTextEdit)
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(500, 230, 291, 161))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.UniTextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.UniTextLayout.setObjectName(_fromUtf8("UniTextLayout"))
        self.UniTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_10)
        self.UniTextEdit.setObjectName(_fromUtf8("UniTextEdit"))
        self.UniTextLayout.addWidget(self.UniTextEdit)
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 400, 461, 80))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.AccomTitleLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.AccomTitleLayout.setObjectName(_fromUtf8("AccomTitleLayout"))
        self.AccomTitleLabel = QtGui.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AccomTitleLabel.setFont(font)
        self.AccomTitleLabel.setObjectName(_fromUtf8("AccomTitleLabel"))
        self.AccomTitleLayout.addWidget(self.AccomTitleLabel)
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(500, 400, 461, 81))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.FundingTitleLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.FundingTitleLayout.setObjectName(_fromUtf8("FundingTitleLayout"))
        self.FundingTitleLabel = QtGui.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FundingTitleLabel.setFont(font)
        self.FundingTitleLabel.setObjectName(_fromUtf8("FundingTitleLabel"))
        self.FundingTitleLayout.addWidget(self.FundingTitleLabel)
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(10, 490, 461, 141))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.AccomTextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.AccomTextLayout.setObjectName(_fromUtf8("AccomTextLayout"))
        self.AccomTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_13)
        self.AccomTextEdit.setObjectName(_fromUtf8("AccomTextEdit"))
        self.AccomTextLayout.addWidget(self.AccomTextEdit)
        self.verticalLayoutWidget_14 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(500, 490, 461, 141))
        self.verticalLayoutWidget_14.setObjectName(_fromUtf8("verticalLayoutWidget_14"))
        self.FundingTextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_14)
        self.FundingTextLayout.setObjectName(_fromUtf8("FundingTextLayout"))
        self.FundingTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_14)
        self.FundingTextEdit.setObjectName(_fromUtf8("FundingTextEdit"))
        self.FundingTextLayout.addWidget(self.FundingTextEdit)
        self.verticalLayoutWidget_15 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 640, 951, 80))
        self.verticalLayoutWidget_15.setObjectName(_fromUtf8("verticalLayoutWidget_15"))
        self.StudentTitleLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_15)
        self.StudentTitleLayout.setObjectName(_fromUtf8("StudentTitleLayout"))
        self.StudentTitleLabel = QtGui.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.StudentTitleLabel.setFont(font)
        self.StudentTitleLabel.setObjectName(_fromUtf8("StudentTitleLabel"))
        self.StudentTitleLayout.addWidget(self.StudentTitleLabel)
        self.verticalLayoutWidget_16 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(20, 730, 301, 121))
        self.verticalLayoutWidget_16.setObjectName(_fromUtf8("verticalLayoutWidget_16"))
        self.Student1TextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_16)
        self.Student1TextLayout.setObjectName(_fromUtf8("Student1TextLayout"))
        self.Student1TextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_16)
        self.Student1TextEdit.setObjectName(_fromUtf8("Student1TextEdit"))
        self.Student1TextLayout.addWidget(self.Student1TextEdit)
        self.verticalLayoutWidget_17 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(340, 730, 301, 121))
        self.verticalLayoutWidget_17.setObjectName(_fromUtf8("verticalLayoutWidget_17"))
        self.Student2TextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_17)
        self.Student2TextLayout.setObjectName(_fromUtf8("Student2TextLayout"))
        self.Student2TextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_17)
        self.Student2TextEdit.setObjectName(_fromUtf8("Student2TextEdit"))
        self.Student2TextLayout.addWidget(self.Student2TextEdit)
        self.verticalLayoutWidget_18 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(660, 730, 291, 121))
        self.verticalLayoutWidget_18.setObjectName(_fromUtf8("verticalLayoutWidget_18"))
        self.Student3TextLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_18)
        self.Student3TextLayout.setObjectName(_fromUtf8("Student3TextLayout"))
        self.Student3TextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_18)
        self.Student3TextEdit.setObjectName(_fromUtf8("Student3TextEdit"))
        self.Student3TextLayout.addWidget(self.Student3TextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.TitleLabel.setText(_translate("MainWindow", "AviateNEducate", None))
        self.EnglishBtn.setText(_translate("MainWindow", "English", None))
        self.GermanBtn.setText(_translate("MainWindow", "German", None))
        self.ZoomBox.setText(_translate("MainWindow", "Enlarge Window", None))
        self.CountryInfoLabel.setText(_translate("MainWindow", "Information on the Country", None))
        self.UniInfoLabel.setText(_translate("MainWindow", "University Options", None))
        self.CountryPicLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.UniPicLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.AccomTitleLabel.setText(_translate("MainWindow", "Accomodation", None))
        self.FundingTitleLabel.setText(_translate("MainWindow", "Funding", None))
        self.StudentTitleLabel.setText(_translate("MainWindow", "Student Experience", None))

